# Generated by Django 3.2.11 on 2022-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220305_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajespage',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=250, verbose_name='Coordenadas'),
        ),
    ]
