# Generated by Django 3.2.11 on 2022-03-11 14:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0010_viajespage_coordenadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'categoría de viajes',
                'verbose_name_plural': 'categorías de viajes',
            },
        ),
        migrations.AlterField(
            model_name='viajespage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.ViajesCategory'),
        ),
    ]
