# Generated by Django 3.2.11 on 2022-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='pie',
            field=models.CharField(blank=True, max_length=500, verbose_name='pie'),
        ),
    ]
